### ISSUE TITLE
Node position incorrect in "Config" Tab

### ISSUE THREAD

**Issue by lbahtarliev** [PaloAltoNetworks/minemeld-core#72]
Hello,
When node of type "Output" is enabled, in "Config" Tab its position is shown as "Processor". However, when the node is disabled, its position correctly matches the type - "Output"

**Comment by jtschichold** [comment]
This is the correct behaviour of the table, because an OUTPUT node should have its output attribute set to disable as there are no downstream nodes. The output attribute of a node determines if the node should send updates to downstream nodes. As an OUTPUT node should not have any downstream node the output attribute should be disabled.

I know this is confusing and misleading, in the next release (0.9.26) the POSITION column has been dropped and replaced by a TYPE column populated with the type of node taken from the prototype. Basically an OUTPUT node will show up as an OUTPUT node even if the output attribute is enabled.

**Comment by jtschichold** [comment]
Have you already checked 0.9.26 ? Do you think it is more clear now ?

**Comment by jtschichold** [comment]
This should be fixed with 0.9.32
